# _config.yml
title: Fun
description: List of fun websites that make the world wide web a better place.
author: Louis Giron
baseurl: ""  # leave empty for user sites
url: "" # leave empty for GitHub Pages to set automatically
